name: mvp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.10.11
  shared_preferences: ^2.5.3
  just_audio: ^0.10.5
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.webp
    - assets/images/
    - assets/music/
    - assets/live2d/hiyori_viewer.html
    - assets/live2d/libs/
    - assets/live2d/hiyori/
    - assets/live2d/hiyori/Hiyori.2048/

fonts:
  - family: ZhuoKai
    fonts:
      - asset: assets/fonts/ZhuoKai.ttf
  - family: ZCOOLKuaiLe-Regular
    fonts:
      - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf

# 配置 flutter_launcher_icons，用项目根目录下的方形图生成各平台图标
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"